name: Daily News Bot

on:
  schedule:
    - cron: '0 22 * * *' # 한국 시간 아침 7시
  workflow_dispatch: # 직접 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 깃허브가 요구하는 최신 노드 버전 강제 설정
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4 # v3 대신 v4 사용

      - name: 파이썬 설치
        uses: actions/setup-python@v5 # v4 대신 v5 사용
        with:
          python-version: '3.10'

      - name: 필요한 도구 설치
        run: pip install requests

      - name: 프로그램 실행
        env:
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
